### ISSUE TITLE
Constant already defined

### ISSUE THREAD

**Issue by Beee4life** [dfactoryplugins/image-watermark#9]
[This line](https://github.com/dfactoryplugins/image-watermark/blob/master/image-watermark.php#L122) (line 128 in v1.6.4) should be wrapped in an IF as follows.

    if ( ! defined( 'IMAGE_WATERMARK_BACKUP_DIR' ) ) {
        define( 'IMAGE_WATERMARK_BACKUP_DIR', apply_filters( 'image_watermark_backup_dir', $upload_dir['basedir'] . DIRECTORY_SEPARATOR . 'iw-backup' ) );
    }

If you run the manual watermark function, as explained in [this topic](https://dfactory.eu/support/topic/do_watermark-inside-functions-php/), then a notice comes it's already defined.

    Constant IMAGE_WATERMARK_BACKUP_DIR already defined in /Users/Beee/HTML/site/webapp/content/plugins/image-watermark/image-watermark.php on line 128

**Comment by bartoszarendt** [comment]
This is not an issue.
Problem in the topic is there's a new plugin instance created using $IW = new Image_Watermark;
While it already exists and should be used like this: 
$IW = $image_watermark;
or $IW = Image_Watermark();
This way you'll not have any error and you'll not create additional plugin instance (it's not needed)

**Comment by Beee4life** [comment]
Thanks for the explanation. Will check.
